import type { Metadata } from 'next'
import './globals.css'
import Header from "@/components/UI/header/Header";
import React from "react";
import Footer from "@/components/UI/footer/Footer";
import {Providers} from "@/redux/app/povider";

export const metadata: Metadata = {
  title: 'Дом мёда',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Providers>
          <Header/>
          {children}
          <Footer/>
      </Providers>
      </body>
    </html>
  )
}
